apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^new$', views.newUserPage, name='newUserPage'),
    url(r'^create_new$', views.createNewUser, name='createNewUser'),
    url(r'^edit$', views.userEditUserPage, name='userEditUserPage'),
    url(r'^edit_profile$', views.edit_profile, name='editProfile'),
    url(r'^edit/(?P<id>\d+)$', views.editUserPage, name='editUserPage'),
    url(r'^edit_user$', views.edit_user, name='editUser'),
    url(r'^edit_password$', views.edit_password, name='editPassword'),
    url(r'^edit__user_password$', views.edit_user_password, name='editUserPassword'),
    url(r'^edit__description$', views.edit_description, name='editDescription'),
    url(r'^show/(?P<id>\d+)$', views.showUserPage, name='showUserPage'),
    url(r'^postMessage$', views.postMessage, name='postMessage'),
    url(r'^postComment/(?P<messageId>\d+)$', views.postComment, name='postComment'),
]

test_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^users/', include('apps.users.urls', namespace='users'))
]

apps/users/models.py
from __future__ import unicode_literals

from django.db import models
from ..login.models import User


class MessageManager(models.Manager):
    def post_message(self, postData, messageReceiver, loggedUser):
        errors = []
        if len(postData['content']) < 2:
            errors.append("Message must be longer than two characters.")

        response_to_views = {}
        if errors:
            response_to_views['status'] = False
            response_to_views['error'] = errors
        else:
            message = self.create(content=postData['content'], author=loggedUser.firstname)
            message.user.add(messageReceiver)
            message.save()
            response_to_views['status'] = True
            response_to_views['message'] = message
        return response_to_views

    def get_messages(self):
        response_to_views = Message.objects.all()
        return response_to_views



class Message(models.Model):
    content = models.TextField()
    author = models.TextField()
    user = models.ManyToManyField(User, related_name="all_user_messages")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = MessageManager()

class CommentManager(models.Manager):
    def post_comment(self, postData, commentReceiver, loggedUser, currentMessage):
        errors = []
        if len(postData['content']) < 2:
            errors.append("Comment must be longer than two characters.")

        response_to_views = {}
        if errors:
            response_to_views['status'] = False
            response_to_views['error'] = errors
        else:
            comment = self.create(content=postData['content'], author=loggedUser.firstname)
            comment.user.add(commentReceiver)
            comment.message.add(currentMessage)
            comment.save()
            print("Comment presumably saved successfully")
            response_to_views['status'] = True
            response_to_views['comment'] = comment
        return response_to_views

    def get_comments(self):
        response_to_views = Message.objects.all()
        return response_to_views

class Comment(models.Model):
    content = models.TextField()
    author = models.TextField()
    user = models.ManyToManyField(User, related_name="all_user_comments")
    message = models.ManyToManyField(Message, related_name="all_message_comments")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = CommentManager()

apps/users/views.py
from django.shortcuts import render, redirect, HttpResponse
from ..login.models import User
from .models import Message
from .models import Comment
from django.contrib import messages
from django.core.urlresolvers import reverse

def newUserPage(request):
    return render(request, 'users/newUserPage.html')

def createNewUser(request):
    if request.method=="POST":
        response_from_models = User.objects.user_validation(request.POST)
        if response_from_models['status']:
            return redirect('login:admin')
        else:
            request.session['error_group'] = True
            for error in response_from_models["error"]:
                messages.error(request, error)
            return redirect('login:admin')
    else:
        return redirect('login:admin')

def edit_user(request):
    if request.method=="POST":
        user = User.objects.get(id=request.session['editUserId'])
        response_from_models = User.objects.edit_validation(request.POST, user)
        if response_from_models['status']:
            return redirect('login:admin')
        else:
            request.session['error_group'] = True
            for error in response_from_models["error"]:
                messages.error(request, error)
            return redirect('login:admin')
    else:
        return redirect('login:admin')

def edit_password(request):
    if request.method=="POST":
        user = User.objects.get(id=request.session['editUserId'])
        response_from_models = User.objects.password_edit_validation(request.POST, user)
        if response_from_models['status']:
            return redirect('login:admin')
        else:
            request.session['error_group'] = True
            for error in response_from_models["error"]:
                messages.error(request, error)
            return redirect('login:admin')
    else:
        return redirect('login:admin')

def edit_profile(request):
    if request.method=="POST":
        user = User.objects.get(id=request.session['id'])
        response_from_models = User.objects.edit_profile(request.POST, user)
        if response_from_models['status']:
            return redirect('login:user')
        else:
            request.session['error_group'] = True
            for error in response_from_models["error"]:
                messages.error(request, error)
            return redirect('login:user')
    else:
        return redirect('login:admin')

def edit_user_password(request):
    if request.method=="POST":
        user = User.objects.get(id=request.session['id'])
        response_from_models = User.objects.edit_user_password(request.POST, user)
        if response_from_models['status']:
            return redirect('login:user')
        else:
            request.session['error_group'] = True
            for error in response_from_models["error"]:
                messages.error(request, error)
            return redirect('login:user')
    else:
        return redirect('login:admin')

def edit_description(request):
    if request.method=="POST":
        user = User.objects.get(id=request.session['id'])
        response_from_models = User.objects.edit_description(request.POST, user)
        return redirect('login:user')
    else:
        return redirect('login:admin')

def editUserPage(request, id):
    request.session['editUserId'] = id
    user = User.objects.get(id=id)
    context = {
        "user": user
    }
    return render(request, "users/editUserPage.html", context)

def userEditUserPage(request):
    user = User.objects.get(id=request.session['id'])
    context = {
        "user": user
    }
    return render(request, "users/userEditUserPage.html", context)

def showUserPage(request, id):
    request.session['showUserId'] = id
    user = User.objects.get(id=id)
    try:
        messages = Message.objects.filter(user=user)
    except:
        messages = None
    print(messages)
    context = {
        "user": user,
        "messages": messages
    }
    return render(request, "users/showUserPage.html", context)

def postMessage(request):
    if request.method=="POST":
        messageReceiver = User.objects.get(id=request.session['showUserId'])
        loggedUser = User.objects.get(id=request.session['id'])
        response_from_models = Message.objects.post_message(request.POST, messageReceiver, loggedUser)
        if response_from_models['status']:
            return redirect(reverse('users:showUserPage', kwargs={'id': request.session['showUserId']}))
        else:
            request.session['error_group'] = True
            for error in response_from_models["error"]:
                messages.error(request, error)
            return redirect(reverse('users:showUserPage', kwargs={'id': request.session['showUserId']}))
    else:
        return redirect(reverse('users:showUserPage', kwargs={'id': request.session['showUserId']}))

def postComment(request, messageId):
    if request.method=="POST":
        commentReceiver = User.objects.get(id=request.session['showUserId'])
        loggedUser = User.objects.get(id=request.session['id'])
        currentMessage = Message.objects.get(id=messageId)
        response_from_models = Comment.objects.post_comment(request.POST, commentReceiver, loggedUser, currentMessage)
        if response_from_models['status']:
            return redirect(reverse('users:showUserPage', kwargs={'id': request.session['showUserId']}))
        else:
            request.session['error_group'] = True
            for error in response_from_models["error"]:
                messages.error(request, error)
            return redirect(reverse('users:showUserPage', kwargs={'id': request.session['showUserId']}))
    else:
        return redirect(reverse('users:showUserPage', kwargs={'id': request.session['showUserId']}))

apps/users/templates/users/editUserPage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit User</title>
    {%load static%}
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
  </head>
  <body>
    <div class="wrapper">
      <h1>Edit user #{{user.id}}</h1>
      <h2>Edit Information</h2>
      <form action='{%url 'users:editUser' %}' method='post'>
        {% csrf_token %}
        <br>Email Address:<input type='text' name='email' value='{{user.email}}'><br>
        <br>First Name:<input type='text' name='firstname' value='{{user.firstname}}'><br>
        <br>Last Name:<input type='text' name='lastname' value='{{user.lastname}}'><br>
        <br><select name='status'>
          <option value='admin'>Admin</option>
          <option value='user'>User</option>
        </select></br>
        <br><input type='submit' value='Edit'></br>
      </form>
      <h2>Change Password</h2>
      <form action='{%url 'users:editPassword' %}' method='post'>
        {% csrf_token %}
        <br>Enter new password:<input type='password' name='password'><br>
        <br>Confirm new password:<input type='password' name='confirm'><br>
        <br><input type='submit' value='Change Password'><br>
      </form>
      <br>
      <form action='{%url 'users:editDescription' %}' method='post'>
        {% csrf_token %}
        Edit Description:<textarea rows="4" cols="50" name='description'></textarea>
        <input type='submit' value='Save'>
      </form>
      <br>
      {% if request.session.loggedin == "Admin" %}
        <a href='/dashboard/admin'>Home</a>
      {% else %}
        <a href='/dashboard'>Home</a>
      {% endif %}
    </div>
  </body>
</html>

apps/users/templates/users/newUserPage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New User</title>
    {%load static%}
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
  </head>
  <body>
    <div class="wrapper">
      <h2>Register</h2>
      <form class="register" action='{%url 'users:createNewUser' %}' method="POST">
          {% csrf_token %}
          Email: <br><input type="text" name="email" value=""><br>
          First Name: <br> <input type="text" name="first_name" value=""><br>
          Last Name: <br><input type="text" name="last_name" value=""><br>
          Password: <br><input type="password" name="password" value=""><br>
          Confirm Password: <br> <input type="password" name="confirm" value=""><br>
          <br>
          <input type="submit" name="" value="Create">
      </form><br>
      {% if request.session.error_group %}
          {% if messages %}
              {% for i in messages %}
                  <p style="color: red;">{{ i }}</p>
              {% endfor %}
          {% endif %}
      {% endif %}
      <a href='/dashboard/admin'>Home</a>
    </div>
  </body>
</html>

apps/users/templates/users/showUserPage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {%load static%}
    <title>{{user.firstname}} {{user.lastname}}</title>
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
  </head>
  <body>
    <div id="msgWrapper">
      <div id="userInfo">
        {% if request.session.loggedin == "Admin" %}
          <a href='/dashboard/admin'>Home</a>
        {% else %}
          <a href='/dashboard'>Home</a>
        {% endif %}
        <h1>{{user.firstname}} {{user.lastname}}</h1>
        <h3>Registered on:  {{user.created_at}}</h3>
        <h3>User ID:  {{user.id}}<h3>
        <h3>Description:  {{user.description}}<h3>
      </div>
      <form action='{%url 'users:postMessage' %}' method="POST">
          {% csrf_token %}
          Leave a message for {{user.firstname}}:
          <br>
          <textarea rows="4" cols="50" name='content'></textarea>
          <input type="submit" value="Post">
      </form><br>
      {%if messages%}
        {% for message in messages %}
            <p>{{message.content}} - {{message.author}}, posted on {{message.created_at}}</p>
          {% for comment in message.all_message_comments.all %}
              <p id="commentP">{{comment.content}} - {{comment.author}}, posted on {{comment.created_at}}</p>
          {% endfor %}
        <form id="commentForm" action='{%url 'users:postComment' messageId=message.id %}' method="POST">
            {% csrf_token %}
            Comment:
            <br>
            <textarea rows="4" cols="50" name='content'></textarea>
            <input type="submit" value="Comment">
        </form><br>
        {% endfor %}
      {% endif %}
      {% if request.session.loggedin == "Admin" %}
      {% else %}
      {% endif %}
    </div>
  </body>
</html>

apps/users/templates/users/userEditUserPage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit Profile</title>
    {%load static%}
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
  </head>
  <body>
    <div class="wrapper">
      <h1>Edit profile</h1>
      <h2>Edit Information</h2>
      <form action='{%url 'users:editProfile' %}' method='post'>
        {% csrf_token %}
        <br>Email Address:<input type='text' name='email' value='{{user.email}}'><br>
        <br>First Name:<input type='text' name='firstname' value='{{user.firstname}}'><br>
        <br>Last Name:<input type='text' name='lastname' value='{{user.lastname}}'><br>
        <br><input type='submit' value='Edit'><br>
      </form>
      <h2>Change Password</h2>
      <form action='{%url 'users:editUserPassword' %}' method='post'>
        {% csrf_token %}
        <br>Enter new password:<input type='password' name='password'><br>
        <br>Confirm new password:<input type='password' name='confirm'><br>
        <br><input type='submit' value='Change Password'><br>
      </form>
      <br>
      <form action='{%url 'users:editDescription' %}' method='post'>
        {% csrf_token %}
        Edit Description:<textarea rows="4" cols="50" name='description'></textarea>
        <input type='submit' value='Save'>
      </form>
      <br>
      {% if request.session.loggedin == "Admin" %}
        <a href='/dashboard/admin'>Home</a>
      {% else %}
        <a href='/dashboard'>Home</a>
      {% endif %}
    </div>
  </body>
</html>