apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create_user$', views.create_user, name='createUser'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^register$', views.register, name='register'),
    url(r'^dashboard$', views.userpage, name='user'),
    url(r'^dashboard/admin$', views.adminpage, name='admin'),
    url(r'^dashboard/admin/remove/(?P<id>\d+)$', views.remove_user, name='removeUser'),
]

apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^new$', views.newUserPage, name='newUserPage'),
    url(r'^create_new$', views.createNewUser, name='createNewUser'),
    url(r'^edit$', views.userEditUserPage, name='userEditUserPage'),
    url(r'^edit_profile$', views.edit_profile, name='editProfile'),
    url(r'^edit/(?P<id>\d+)$', views.editUserPage, name='editUserPage'),
    url(r'^edit_user$', views.edit_user, name='editUser'),
    url(r'^edit_password$', views.edit_password, name='editPassword'),
    url(r'^edit__user_password$', views.edit_user_password, name='editUserPassword'),
    url(r'^edit__description$', views.edit_description, name='editDescription'),
    url(r'^show/(?P<id>\d+)$', views.showUserPage, name='showUserPage'),
    url(r'^postMessage$', views.postMessage, name='postMessage'),
    url(r'^postComment/(?P<messageId>\d+)$', views.postComment, name='postComment'),
]

test_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^users/', include('apps.users.urls', namespace='users'))
]

apps/login/models.py
from __future__ import unicode_literals

from django.db import models
import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
import hashlib
import binascii
from os import urandom

class UserManager(models.Manager):
    def get_users(self):
        response_to_views = User.objects.all()
        return response_to_views

    def remove_user(self, id):
        response_to_views = User.objects.get(id=id).delete()
        return response_to_views

    def edit_validation(self, postData, user):
        errors = []

        if len(postData['firstname']) < 1:
            errors.append("First name field cannot be blank.")

        if len(postData['lastname']) < 1:
            errors.append("Last name field cannot be blank.")

        if len(postData['email']) < 1:
            errors.append("Email field cannot be blank.")
        if not EMAIL_REGEX.match(postData['email']):
            errors.append("Email address is not valid.")

        # Existing email validation should go here

        response_to_views = {}
        if errors:
            response_to_views['status'] = False
            response_to_views['error'] = errors
        else:
            user.email = postData['email']
            user.firstname = postData['firstname']
            user.lastname = postData['lastname']
            if postData['status'] == 'admin':
                user.admin = True
            if postData['status'] == 'user':
                user.admin = False
            user.save()
            response_to_views['status'] = True
            response_to_views['user'] = user
        return response_to_views

    def password_edit_validation(self, postData, user):
        errors = []

        if len(postData['password']) < 4:
            errors.append("Password must be at least 4 charaters.")
        if len(postData['confirm']) < 1:
            errors.append("Please confirm your password.")
        if not postData["password"] == postData["confirm"]:
            errors.append("Your passwords do not match.")

        response_to_views = {}
        if errors:
            response_to_views['status'] = False
            response_to_views['error'] = errors
        else:
            hashed_password = hashlib.md5(postData['password'].encode('utf-8')).hexdigest();
            user.password = hashed_password
            user.save()
            response_to_views['status'] = True
            response_to_views['user'] = user
        return response_to_views

    def edit_profile(self, postData, user):
        errors = []

        if len(postData['firstname']) < 1:
            errors.append("First name field cannot be blank.")

        if len(postData['lastname']) < 1:
            errors.append("Last name field cannot be blank.")

        if len(postData['email']) < 1:
            errors.append("Email field cannot be blank.")
        if not EMAIL_REGEX.match(postData['email']):
            errors.append("Email address is not valid.")

        # Existing email validation should go here

        response_to_views = {}
        if errors:
            response_to_views['status'] = False
            response_to_views['error'] = errors
        else:
            user.email = postData['email']
            user.firstname = postData['firstname']
            user.lastname = postData['lastname']
            user.save()
            response_to_views['status'] = True
            response_to_views['user'] = user
        return response_to_views

    def edit_user_password(self, postData, user):
        errors = []

        if len(postData['password']) < 4:
            errors.append("Password must be at least 4 charaters.")
        if len(postData['confirm']) < 1:
            errors.append("Please confirm your password")
        if not postData["password"] == postData["confirm"]:
            errors.append("Your passwords do not match")

        response_to_views = {}
        if errors:
            response_to_views['status'] = False
            response_to_views['error'] = errors
        else:
            hashed_password = hashlib.md5(postData['password'].encode('utf-8')).hexdigest();
            user.password = hashed_password
            user.save()
            response_to_views['status'] = True
            response_to_views['user'] = user
        return response_to_views

    def edit_description(self, postData, user):

        response_to_views = {}
        user.description = postData['description']
        user.save()
        response_to_views['user'] = user
        return response_to_views

    def user_validation(self, postData):
        errors = []

        if len(postData['first_name']) < 1:
            errors.append("First name field cannot be blank.")

        if len(postData['last_name']) < 1:
            errors.append("Last name field cannot be blank.")

        if len(postData['email']) < 1:
            errors.append("Email field cannot be blank.")
        if not EMAIL_REGEX.match(postData['email']):
            errors.append("Email address is not valid.")
        try:
            User.objects.get(email = postData['email'])
            errors.append("Email has already been registered")
        except:
            pass

        if len(postData['password']) < 4:
            errors.append("Password must be at least 4 characters.")
        if len(postData['confirm']) < 1:
            errors.append("Please confirm your password.")
        if not postData["password"] == postData["confirm"]:
            errors.append("Your passwords do not match.")


        response_to_views = {}
        if errors:
            response_to_views['status'] = False
            response_to_views['error'] = errors
        else:
            hashed_password = hashlib.md5(postData['password'].encode('utf-8')).hexdigest();
            user = self.create(firstname=postData['first_name'], lastname=postData['last_name'], email=postData['email'], password=hashed_password)
            if user.email == "bradvsherman@gmail.com":
                user.admin = True
                user.save()
            response_to_views['status'] = True
            response_to_views['user'] = user
        return response_to_views

    def login_validation(self, postData):

        login_errors = []
        hashed_password = hashlib.md5(postData['password'].encode('utf-8')).hexdigest();

        try:
            User.objects.get(email=postData["email"])
        except:
            login_errors.append("Email incorrect.")
        try:
            User.objects.get(email=postData["email"], password=hashed_password)
        except:
            login_errors.append("Password incorrect.")

        response_to_views = {}
        if login_errors:
            response_to_views['status'] = False
            response_to_views['errors'] = login_errors
        else:
            user = User.objects.get(email=postData["email"])
            response_to_views['status'] = True
            response_to_views['user'] = user
        return response_to_views

class User(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    password = models.CharField(max_length = 100)
    admin = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/login/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import User
from django.contrib import messages

def index(request):
    return render(request, "login/signin.html")

def register(request):
    return render(request, "login/register.html")

def userpage(request):
    request.session['loggedin'] == "User"
    all_users = User.objects.get_users()
    context = {
        'users': all_users
    }
    return render(request, "login/userpage.html", context)


def adminpage(request):
    request.session['loggedin'] == "Admin"
    all_users = User.objects.get_users()
    context = {
        'users': all_users
    }
    return render(request, "login/adminpage.html", context)

def create_user(request):
    if request.method=="POST":
        response_from_models = User.objects.user_validation(request.POST)
        if response_from_models['status']:
            if response_from_models['user'].admin == True:
                request.session['loggedin'] = "Admin"
            else:
                request.session['loggedin'] = "User"
            request.session["id"] = response_from_models["user"].id
            pass
        else:
            request.session['error_group'] = True
            for i in response_from_models["error"]:
                messages.error(request, i)
            return redirect('login:register')
    else:
        return redirect('/')
    if request.session['loggedin'] == "Admin":
        return redirect('login:admin')
    if request.session['loggedin'] == "User":
        return redirect('login:user')

def remove_user(request, id):
    User.objects.remove_user(id)
    return redirect('login:admin')

def login(request):
    if request.method=="POST":
        response_from_models = User.objects.login_validation(request.POST)
        if response_from_models['status']:
            if response_from_models['user'].admin == True:
                request.session['loggedin'] = "Admin"
            else:
                request.session['loggedin'] = "User"
            request.session["id"] = response_from_models["user"].id
            pass
        else:
            request.session['error_group'] = False
            for i in response_from_models["errors"]:
                messages.error(request, i)
            return redirect('/')
    else:
        return redirect('/')
    if request.session['loggedin'] == "Admin":
        return redirect('login:admin')
    if request.session['loggedin'] == "User":
        return redirect('login:user')

def logout(request):
    request.session.flush()
    return redirect('/')

apps/login/templates/login/adminpage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Admin Dashboard</title>
    {%load static%}
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
  </head>
  <body>
    <div class='wrapper'>
      <h1>Manage Users</h1>
      <button><a href='{%url 'users:newUserPage' %}'>Add new</a></button>
      <table>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Created At</th>
          <th>Admin</th>
          <th>Actions</th>
        </tr>
        {% for user in users %}
        <tr>
          <td>{{user.id}}</td>
          <td><a href="{%url 'users:showUserPage' id=user.id %}">{{user.firstname}} {{user.lastname}}</a></td>
          <td>{{user.email}}</td>
          <td>{{user.created_at}}</td>
          {% if user.admin == True %}
            <td>Admin</td>
          {% else %}
            <td>User</td>
          {% endif %}
          <td><a href="{%url 'users:editUserPage' id=user.id %}">Edit</a> | <a href="{%url 'login:removeUser' id=user.id %}">Remove</a></td>
        </tr>
        {% endfor %}
        {% for message in messages %}
          {{message}}
        {% endfor %}
      </table>
      <a href='{%url 'login:logout' %}'>Logout</a>
    </div>
  </body>
</html>

apps/login/templates/login/register.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Signin Page</title>
        {%load static%}
        <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
    </head>
    <body>
        <div class="wrapper">
            <div class="register">
                <h1>Welcome to the user dashboard.</h1>
                <h2>Register:</h2>
                <form class="register" action='{%url 'login:createUser' %}' method="POST">
                    {% csrf_token %}
                    First Name: <br> <input type="text" name="first_name" value=""><br>
                    Last Name: <br><input type="text" name="last_name" value=""><br>
                    Email: <br><input type="text" name="email" value=""><br>
                    Password: <br><input type="password" name="password" value=""><br>
                    Confirm Password: <br> <input type="password" name="confirm" value=""><br>
                    <input class='submit' type="submit" name="" value="Register">
                </form><br>
                <a href='/'>Already have an account?  Login</a>
                {% if request.session.error_group %}
                    {% if messages %}
                        {% for i in messages %}
                            <p style="color: red;">{{ i }}</p>
                        {% endfor %}
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </body>
</html>

apps/login/templates/login/signin.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Signin Page</title>
        {%load static%}
        <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
    </head>
    <body>
        <div class="wrapper">
            <div class="login">
                <h1>Welcome to the user dashboard.</h1>
                <h2>Sign In:</h2>
                <form class="login" action='{%url 'login:login' %}' method="post">
                    {% csrf_token %}
                    Email: <br><input type="text" name="email"><br>
                    Password: <br><input type="password" name="password"><br>
                    <input class='submit' type="submit" name="submit" value="Sign In">
                </form>
                <br>
                <a href='register'>Don't have an account?  Register.</a>
                {% if not request.session.error_group %}
                    {% if messages %}
                        {% for i in messages %}
                            <p style="color: red;">{{ i }}</p>
                        {% endfor %}
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </body>
</html>

apps/login/templates/login/userpage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Dashboard</title>
    {%load static%}
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
  </head>
  <body>
    <div class='wrapper'>
      <h1>Manage Users</h1>
      <table>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Created At</th>
          <th>Admin</th>
          <th>Actions</th>
        </tr>
        {% for user in users %}
        <tr>
          <td>{{user.id}}</td>
          <td><a href="{%url 'users:showUserPage' id=user.id %}">{{user.firstname}} {{user.lastname}}</a></td>
          <td>{{user.email}}</td>
          <td>{{user.created_at}}</td>
          {% if user.admin == True %}
            <td>Admin</td>
          {% else %}
            <td>User</td>
          {% endif %}
          {% if user.id == request.session.id %}
          <td><a href="{%url 'users:userEditUserPage' %}">Edit</a></td>
          {% else %}
          <td></td>
          {% endif %}
        </tr>
        {% endfor %}
      </table>
      <a href='{%url 'login:logout' %}'>Logout</a>
    </div>
  </body>
</html>